version: '3.8'

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: portfolio_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/portfolio_db
      SECRET_KEY: super-secret-key # Change this in production!
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      FASTAPI_SERVICE_URL: http://backend:8000 # For communication within Docker network
      REACT_APP_FASTAPI_URL: http://localhost:8000 # For local development access from browser
    depends_on:
      - backend
    restart: always
    # This is for hot-reloading in development with Docker volumes on some systems
    # Uncomment if you face issues with live updates
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    # environment:
    #   CHOKIDAR_USEPOPOLLING: true # For hot reloading on some OS (e.g., Windows Subsystem for Linux)

volumes:
  db-data:
